"""creating tabels

Revision ID: a26ccac2683f
Revises:
Create Date: 2022-08-14 03:32:17.065213

"""
import sqlalchemy as sa  # type: ignore
from alembic import op
from sqlalchemy.dialects import postgresql  # type: ignore

# revision identifiers, used by Alembic.
revision = 'a26ccac2683f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ext_auth',
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('auth_source', sa.String(length=255), nullable=False),
                    sa.Column('auth_source_url', sa.String(length=255), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id'),
                    schema='customers'
                    )
    op.create_table('roles',
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('role', sa.String(length=64), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id'),
                    schema='customers'
                    )
    op.create_table('users',
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('login', sa.String(), nullable=True),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('email', sa.String(length=64), nullable=True),
                    sa.Column('created_at', sa.String(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(), nullable=True),
                    sa.Column('role_id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('user_ext_id', sa.String(), nullable=True),
                    sa.Column('ext_auth_source_id', postgresql.UUID(as_uuid=True), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('email_notification', sa.Boolean(), nullable=False),
                    sa.Column('ws_notification', sa.Boolean(), nullable=False),
                    sa.Column('confirm_email_status', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['ext_auth_source_id'], ['customers.ext_auth.id'], ),
                    sa.ForeignKeyConstraint(['role_id'], ['customers.roles.id'], ),
                    sa.PrimaryKeyConstraint('id', 'is_active'),
                    sa.UniqueConstraint('id', 'is_active'),
                    sa.UniqueConstraint('email', 'is_active'),
                    schema='customers',
                    postgresql_partition_by='LIST (is_active)'
                    )
    op.create_table('users_logs',
                    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
                    sa.Column('user_agent', sa.String(length=255), nullable=True),
                    sa.Column('user_action', sa.String(length=64), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('id'),
                    schema='customers'
                    )
    op.execute("CREATE TABLE customers.users_is_active PARTITION OF customers.users for values in (true);")
    op.execute("CREATE TABLE customers.users_is_not_active PARTITION OF customers.users for values in (false);")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_logs', schema='customers')
    op.drop_table('users', schema='customers')
    op.drop_table('roles', schema='customers')
    op.drop_table('ext_auth', schema='customers')
    # ### end Alembic commands ###
