FROM python:3.9

RUN apt-get update 
RUN apt install libpq-dev
RUN mkdir -p /home/flask
WORKDIR /home/flask

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

EXPOSE 5000

COPY ./requirements.txt /
RUN python -m pip install --upgrade pip
RUN pip install -r /requirements.txt

#COPY . .
#
#CMD ["gunicorn", "--workers", "5", "--bind", "0.0.0.0:5000", "wsgi:app"]